name: Build WordJumbleBot

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: amd64
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Get Bun cache
        uses: actions/cache@v5
        env:
          BUN_INSTALL_CACHE_DIR: /tmp/.bun-cache
        with:
          key: bun-${{ github.event.repository.name }}-${{ hashFiles('./bun.lock') }}
          path: ${{ env.BUN_INSTALL_CACHE_DIR }}

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Install dependencies
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: bun install --frozen-lockfile

      - name: Linting
        run: bun run lint:ci

  amd64:
    needs: [ check ]
    runs-on: amd64
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Log into repository
        uses: docker/login-action@v4
        with:
          registry: git.postfmly.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        run: docker buildx build --platform linux/amd64 --tag git.postfmly.com/admin/wordjumblebot:amd64 --push .

  arm64:
    needs: [ check ]
    runs-on: arm64
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Log into repository
        uses: docker/login-action@v4
        with:
          registry: git.postfmly.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        run: docker buildx build --platform linux/arm64 --tag git.postfmly.com/admin/wordjumblebot:arm64 --push .

  manifest:
    needs: [ amd64, arm64 ]
    runs-on: amd64
    steps:
      - name: Log into repository
        uses: docker/login-action@v4
        with:
          registry: git.postfmly.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Create manifest
        run: |
          docker manifest create \
            git.postfmly.com/admin/wordjumblebot:latest \
            git.postfmly.com/admin/wordjumblebot:amd64 \
            git.postfmly.com/admin/wordjumblebot:arm64

      - name: Push manifest
        run: docker manifest push git.postfmly.com/admin/wordjumblebot:latest
